#!/usr/bin/env bash
# Put the rubric grader (/grader + /grader/api/*) online behind a login.
#
# Run ON the instance from the repo root, with the stack already up:
#     bash deploy/enable-grader.sh [username]        # default username: teacher
#
# It hashes a password with the running Caddy (bcrypt), writes
# deploy/sites/grader.caddy (git-ignored; the Caddyfile imports deploy/sites/*.caddy)
# and reloads Caddy. DemoBuilder stays open; only /grader asks for the login.
# Re-run to change the password. To take the grader offline again:
#     rm deploy/sites/grader.caddy && docker compose -f deploy/docker-compose.yml restart caddy
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
COMPOSE=(docker compose -f deploy/docker-compose.yml)
USER_NAME="${1:-teacher}"
[[ "$USER_NAME" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "Username may use letters, digits, . _ - only." >&2; exit 1; }

read -r -s -p "New password for '${USER_NAME}' (10+ characters): " PW; echo
read -r -s -p "Repeat it: " PW2; echo
[ "$PW" = "$PW2" ] || { echo "Passwords differ." >&2; exit 1; }
[ "${#PW}" -ge 10 ] || { echo "Use at least 10 characters." >&2; exit 1; }

HASH="$("${COMPOSE[@]}" exec -T caddy caddy hash-password --plaintext "$PW" | tr -d '\r\n')"
[[ "$HASH" == \$2* ]] || { echo "Unexpected hash output from Caddy: $HASH" >&2; exit 1; }

mkdir -p deploy/sites
umask 077
cat > deploy/sites/grader.caddy <<EOF
# Generated by deploy/enable-grader.sh. Do not commit (git-ignored).
@grader path /grader /grader/*
handle @grader {
	basic_auth {
		${USER_NAME} ${HASH}
	}
	@graderapi path /grader/api/*
	handle @graderapi {
		reverse_proxy backend:8000 {
			flush_interval -1
		}
	}
	handle {
		encode zstd gzip
		root * /srv
		try_files {path} /index.html
		file_server
	}
}
EOF
chmod 644 deploy/sites/grader.caddy   # Caddy (another user in the container) must read it

"${COMPOSE[@]}" exec -T caddy caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
"${COMPOSE[@]}" exec -T caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
echo "Grader is online at https://<your SITE_ADDRESS>/grader (user: ${USER_NAME})."
